from pydantic import BaseModel, Field
from typing import List

class AgentDefinition(BaseModel):
    """Defines a specialized agent to be created dynamically."""
    name: str = Field(..., description="The unique name of the agent.")
    role: str = Field(..., description="The role and system instructions for the agent.")
    tools: List[str] = Field(default=[], description="List of tool names assigned to this agent.")

class Task(BaseModel):
    """Represents a single step in the plan."""
    id: str = Field(..., description="Unique identifier for the task (e.g., 'task_1').")
    description: str = Field(..., description="The instruction describing what to do.")
    agent_name: str = Field(..., description="The name of the agent assigned to this task.")
    dependencies: List[str] = Field(default=[], description="List of task IDs that must be completed before this task.")

class Plan(BaseModel):
    """The complete plan generated by the Architect."""
    title: str = Field(..., description="A short, descriptive title for the execution (3-5 words).")
    agents: List[AgentDefinition] = Field(..., description="The definitions of agents to staff the project.")
    tasks: List[Task] = Field(..., description="The list of tasks to be executed.")
